version: '3.8'

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - ${DOCKER_NETWORK:-app_network}
    command: ["bun", "run", "migrate:all"]
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_HOST_PORT:-3000}:${APP_CONTAINER_PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - ORIGIN=${ORIGIN}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - AUTH_HOST=${AUTH_HOST}
      - AUTH_PORT=${AUTH_PORT}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - TEST_USERS=${TEST_USERS}
      - TEST_ORG=${TEST_ORG}
      - EMAIL_SERVICE_PROVIDER=${EMAIL_SERVICE_PROVIDER}
      - AZURE_COMMUNICATION_CONNECTION_STRING=${AZURE_COMMUNICATION_CONNECTION_STRING}
      - AZURE_COMMUNICATION_FROM_EMAIL=${AZURE_COMMUNICATION_FROM_EMAIL}
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - ${DOCKER_NETWORK:-app_network}


networks:
  ${DOCKER_NETWORK:-app_network}: