/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CenterLocation = "Australia" | "Nepal" | "UK" | "USA";

export type EventRegistrationMode = "PRE_REGISTRATION" | "WALK_IN";

export type EventStatus = "ACTIVE" | "CLOSED" | "DRAFT";

export type GenderType = "female" | "male" | "other" | "prefer_not_to_say";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MembershipType = "Board Member" | "General Member" | "Honorary Member" | "Life Time";

export type PersonTitle = "dharma_dhar" | "sahayak_dharmacharya" | "sahayak_samathacharya";

export type PersonType = "attended_orientation" | "contact" | "interested" | "sangha_member";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "krama_instructor" | "viewer";

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Empowerment {
  class: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string;
  description: string | null;
  form: string | null;
  id: Generated<string>;
  last_updated_by: string;
  major_empowerment: Generated<boolean>;
  name: string;
  prerequisites: string | null;
  type: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Event {
  category_id: string;
  closed_at: Timestamp | null;
  closed_by: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string;
  description: string | null;
  empowerment_id: string | null;
  end_date: Timestamp;
  guru_id: string | null;
  id: Generated<string>;
  last_updated_by: string;
  metadata: Generated<Json>;
  name: string;
  registration_mode: EventRegistrationMode;
  start_date: Timestamp;
  status: Generated<EventStatus>;
  updated_at: Generated<Timestamp | null>;
}

export interface EventAttendance {
  checked_in_at: Generated<Timestamp>;
  checked_in_by: string;
  event_attendee_id: string;
  event_day_id: string;
  id: Generated<string>;
}

export interface EventAttendee {
  empowerment_record_id: string | null;
  event_id: string;
  id: Generated<string>;
  is_cancelled: Generated<boolean>;
  metadata: Generated<Json>;
  notes: string | null;
  person_id: string;
  received_empowerment: Generated<boolean>;
  registered_at: Generated<Timestamp | null>;
  registered_by: string;
  registration_mode: EventRegistrationMode;
}

export interface EventCategory {
  code: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  name: string;
  requires_full_attendance: Generated<boolean>;
  updated_at: Generated<Timestamp | null>;
}

export interface EventDay {
  created_at: Generated<Timestamp | null>;
  day_number: number;
  event_date: Timestamp;
  event_id: string;
  id: Generated<string>;
}

export interface Group {
  createdAt: Generated<Timestamp | null>;
  createdBy: string;
  description: string | null;
  id: Generated<string>;
  lastUpdatedBy: string;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Guru {
  createdAt: Generated<Timestamp | null>;
  createdBy: string;
  guruName: string;
  id: Generated<string>;
  lastUpdatedBy: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface Person {
  address: string;
  center: CenterLocation;
  /**
   * Country of residence
   */
  country: string | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: string;
  emailId: string | null;
  /**
   * Name of emergency contact person
   */
  emergencyContactName: string | null;
  /**
   * Phone number of emergency contact person
   */
  emergencyContactPhone: string | null;
  /**
   * Relationship to the emergency contact (e.g., spouse, parent, sibling)
   */
  emergencyContactRelationship: string | null;
  firstName: string;
  gender: GenderType | null;
  /**
   * Whether the person has a membership card (for Sangha members)
   */
  hasMembershipCard: boolean | null;
  id: Generated<string>;
  is_krama_instructor: Generated<boolean | null>;
  krama_instructor_person_id: string | null;
  /**
   * Preferred language for communication
   */
  languagePreference: string | null;
  lastName: string;
  lastUpdatedBy: string;
  /**
   * Membership card number for Sangha members
   */
  membershipCardNumber: string | null;
  /**
   * Type of membership for Sangha members
   */
  membershipType: MembershipType | null;
  /**
   * Middle name of the person
   */
  middleName: string | null;
  /**
   * Nationality of the person
   */
  nationality: string | null;
  /**
   * Additional notes or comments about the person
   */
  notes: string | null;
  /**
   * Occupation of the person
   */
  occupation: string | null;
  personCode: string | null;
  phoneNumber: string | null;
  photo: string | null;
  /**
   * Primary phone number of the person
   */
  primaryPhone: string | null;
  /**
   * Free form text field indicating who referred this person
   */
  referredBy: string | null;
  /**
   * Dharma name given during refuge ceremony (for Sangha members)
   */
  refugeName: string | null;
  /**
   * Secondary phone number of the person
   */
  secondaryPhone: string | null;
  /**
   * Dharma title for Sangha members
   */
  title: PersonTitle | null;
  type: Generated<PersonType>;
  updatedAt: Generated<Timestamp | null>;
  yearOfBirth: number | null;
  /**
   * Year when refuge was taken (for Sangha members)
   */
  yearOfRefuge: number | null;
  /**
   * Calendar type for year of refuge (BS or AD)
   */
  yearOfRefugeCalendarType: string | null;
}

export interface PersonEmpowerment {
  created_at: Generated<Timestamp | null>;
  created_by: string;
  empowerment_id: string;
  end_date: Timestamp | null;
  guru_id: string;
  id: Generated<string>;
  last_updated_by: string;
  person_id: string;
  start_date: Timestamp;
  updated_at: Generated<Timestamp | null>;
}

export interface PersonGroup {
  addedBy: string;
  groupId: string;
  id: Generated<string>;
  joinedAt: Generated<Timestamp | null>;
  personId: string;
}

export interface SchemaMigrations {
  version: string;
}

export interface Session {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Timestamp;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  /**
   * Role of the user for access control (admin, krama_instructor, viewer)
   */
  role: Generated<UserRole>;
  updatedAt: Timestamp;
}

export interface Verification {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface DB {
  account: Account;
  empowerment: Empowerment;
  event: Event;
  event_attendance: EventAttendance;
  event_attendee: EventAttendee;
  event_category: EventCategory;
  event_day: EventDay;
  group: Group;
  guru: Guru;
  person: Person;
  person_empowerment: PersonEmpowerment;
  person_group: PersonGroup;
  schema_migrations: SchemaMigrations;
  session: Session;
  user: User;
  verification: Verification;
}
