name = "satoritest1"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[env.production]
name = "satoritest1"

# Build configuration
[[pages_build_commands]]
command = "NODE_OPTIONS=--max-old-space-size=8192 pnpm build"

# Environment variables (add your specific ones here)
# [env.production.vars]
# API_URL = "api.satori.byomakusuma.com"

# Custom headers for SPA routing
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback for React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200