name = "portal"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[env.production]
name = "portal"

# Environment variables (add your specific ones here)
[env.production.vars]
VITE_API_URL = "https://api.portal.byomakusuma.com"

# SPA fallback for React Router
#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200