name = "satori"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[env.production]
name = "satori"

# Environment variables (add your specific ones here)
# [env.production.vars]
# API_URL = "api.satori.byomakusuma.com"

# SPA fallback for React Router
#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200